name: GoSec Analysis
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/*.mod"

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gosec action
        uses: Luiggi33/gosec-enhanced@v0.1.0
